
server:
  port: 8090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
        simple:
          default-requeue-rejected: false
          # retry:
          #   enabled: true
          #   initial-interval: 2s
          #   multiplier: 2
          #   max-attempts: 3
